import Head from 'next/head';
import Image from 'next/image';
import { AiFillFacebook, AiFillGithub, AiFillInstagram } from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from 'react';
import kimramen from '../public/kameramen.png';
import botret from '../public/kimira.png';
import kawinan from '../public/kawinan.png';
import design from '../public/design.png';
import pic1 from '../public/pic1.jpg';
import pic2 from '../public/pic2.jpg';
import pic3 from '../public/pic3.jpg';
import pic4 from '../public/pic4.jpg';
import pic5 from '../public/pic5.jpg';
import pic6 from '../public/pic6.jpg';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>HalfNugget Media | Your Moment is Precious</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ini buwat halaman utama */}
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons dark:text-rose-700">HNM</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-red-400 to-red-600 text-white px-4 py-2 rounded-md ml-8" href="#">
                  Hubungi Kami
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-red-600 font-medium md:text-6xl dark:text-rose-700">The HalfNugget Media</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Photo & Video Productions.</h3>
            <p className="text-md py-5 leading-8 text-gray-700 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              Abadikan momen terbaik anda yang tak terlupakan dengan menakjubkan bersama Perusahaan Kami, Karena kepuasan pelanggan adalah kewajiban kami.
            </p>
            <div className="text-5xl flex justify-center gap-16 text-gray-600 dark:text-gray-400">
              <AiFillFacebook />
              <AiFillGithub />
              <AiFillInstagram />
            </div>
            <div className="relative mx-auto bg-gradient-to-b  from-red-400 rounded-full w-80 h-80 mt-20 mb-20 overflow-hidden md:h-96 md:w-96">
              <Image src={kimramen} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        {/* pelayanan kami */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Pelayanan Kami</h3>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-200">
              Berpengalaman di Bidang Fotografi Dan Videografi Sejak 2016, The HalfNugget Media telah dipercayai klien kami untuk selalu menjadi andalan untuk mengabadikan momen mereka.
              <span className="text-red-500"> Klien & Agensi</span> Memercayai Kami Untuk <span className="text-red-500">Jasa Dokumentasi </span>
              berbagai acara dan kegiatan baik dari yang Formal Maupun Nonformal{' '}
            </p>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-200">Kami Menyediakan berbagai jasa produksi Foto & Video, Mulai dari Company Profile, Wedding & Pre Wedding, Product Advertising dan masih banyak lagi.</p>
          </div>

          {/* carrdddssss */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Stunning Cinematic</h3>
              <p className="py-2 dark:text-white">Menyajikan penyorotan kamera dengan angle dan take terbaik yang memanjakan mata.</p>
              <h4 className="py-4 text-red-600">Perangkat yang Kami Gunakan</h4>
              <p className="text-gray-700 py-1 dark:text-white">Sony A7R</p>
              <p className="text-gray-700 py-1 dark:text-white">Rode Pro Rycote</p>
              <p className="text-gray-700 py-1 dark:text-white">Sony Lens</p>
              <p className="text-gray-700 py-1 dark:text-white">DJI Ronin S II</p>
              <p className="text-gray-700 py-1 dark:text-white">Saramonic Blink 500</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={botret} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Amazing Portraits</h3>
              <p className="py-2 dark:text-white">Memberikan hasil potret terbaik untuk diabadikan</p>
              <h4 className="py-4 text-red-600">Perangkat yang Kami Gunakan</h4>
              <p className="text-gray-700 py-1 dark:text-white">EOS 5D MKIII</p>
              <p className="text-gray-700 py-1 dark:text-white">Sony Lens</p>
              <p className="text-gray-700 py-1 dark:text-white">DJI Ronin S II</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={kawinan} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Wedding Documentation</h3>
              <p className="py-2 dark:text-white">Abadikan momen pernikahan ada dengan Kami</p>
              <h4 className="py-4 text-red-600">Perangkat yang Kami Gunakan</h4>
              <p className="text-gray-700 py-1 dark:text-white">Sony A7s MK.IV</p>
              <p className="text-gray-700 py-1 dark:text-white">Rode Pro Rycote</p>
              <p className="text-gray-700 py-1 dark:text-white">Sony Lens</p>
              <p className="text-gray-700 py-1 dark:text-white">DJI Ronin S II</p>
              <p className="text-gray-700 py-1 dark:text-white">DJI Mavic Pro</p>
              <p className="text-gray-700 py-1 dark:text-white">Saramonic Blink 500</p>
            </div>
          </div>
        </section>

        {/* Portfolio */}
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-200 ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-200">
              Berpengalaman di Bidang Fotografi Dan Videografi Sejak 2016, The HalfNugget Media telah dipercayai klien kami untuk selalu menjadi andalan untuk mengabadikan momen mereka.
              <span className="text-red-500"> Klien & Agensi</span> Memercayai Kami Untuk <span className="text-red-500">Jasa Dokumentasi </span>
              berbagai acara dan kegiatan baik dari yang Formal Maupun Nonformal
            </p>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-200">Kami Menyediakan berbagai jasa produksi Foto & Video, Mulai dari Company Profile, Wedding & Pre Wedding, Product Advertising dan masih banyak lagi.</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={pic1} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={pic2} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={pic3} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={pic4} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={pic5} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={pic6} />
            </div>
          </div>
        </section>

        {/* footernya gausa sulit sulit lah ya */}

        <section>
          <footer>
            <h4 className="text-center text-sm text-gray-700 py-1 dark:text-white">created by halfnuggetxx</h4>
          </footer>
        </section>
      </main>
    </div>
  );
}
